[package]
name = "cwillsey/rorg"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
caretaker = "cwillsey06/caretaker@1.0.2"
promise = "evaera/promise@4.0.0"
signal = "sleitnick/signal@1.2.0"